  # JS divergence calculation. Original code:
  #
  # http://stackoverflow.com/questions/11226627/jensen-shannon-divergence-in-r

#' Calculate the Jensen-Shannon divergence.
#'
#' Given two probability distributions, calculate the Jensen-Shannon (JS)
#' divergence between them.
#'
#' @param p,q Numerical vectors representing the probability distributions.
#' @return A numeric for the JS divergence between the vectors.
#' @seealso \code{\link{calculateDrJsDivergence}}
#' @export
calculateJsDivergence <- function(p, q) {
  # Verify that p and q are probability distributions.
  if (!isTRUE(all.equal(sum(p), 1)) ||
      !isTRUE(all.equal(sum(q), 1)) ||
      any(p < 0) || any(q < 0)) {
    stop("p and q should be probability distributions")
  }

  # Calculate the JS divergence.
  m <- 0.5 * (p + q)
  0.5 * (sum(p * log(p / m)) + sum(q * log(q / m)))
}

#' Calculate the probability distribution of a matrix.
#'
#' Calculate the two-dimensional density of a matrix using kernel density
#' estimation (KDE), convert it into a vector, and normalize it to sum 1.
#'
#' @param mtx Numeric matrix for which to calculate the probability
#' distribution.
#' @param n Number of grid points for KDE.
#' @param lims The limits of the rectangle covered by the KDE.
#' @return A one-dimensional numeric vector for the probability density.
.calculateMatrixKde <- function(mtx, n = 25, lims = NULL) {
  if (is.null(lims)) {
    stop("Kernel density estimation limits parameter is missing")
  }

  density <- MASS::kde2d(mtx[, 1], mtx[, 2], n = n, lims = lims)
  density_vector <- as.vector(density$z)
  density_vector / sum(density_vector)
}

#' Jensen-Shannon divergence between dimensionality reduction maps.
#'
#' Calculate the Jensen-Shannon (JS) divergence between two two-dimensional maps
#' that were generated by a dimensionality reduction (DR) method.
#'
#' @param x,y Two-dimensional numeric matrices to compare.
#' @inheritParams .calculateMatrixKde
#' @return A numeric for the JS divergence between the maps.
#' @seealso \code{\link{calculateJsDivergence}}
calculateDrJsDivergence <- function(x, y, n = 2 ^ 8) {
  if (ncol(x) != 2) {
    stop("x should be a two-dimensional numeric matrix")
  }
  if (ncol(y) != 2) {
    stop("x should be a two-dimensional numeric matrix")
  }

  # Use range over combined data as KDE limits.
  lims <- c(range(c(x[, 1], y[, 1])), range(c(x[, 2], y[, 2])))
  # Convert matrices to probability distributions.
  x_prob <- .calculateMatrixKde(x, n, lims)
  y_prob <- .calculateMatrixKde(y, n, lims)

  calculateJsDivergence(x_prob, y_prob)
}
